repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8.git
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-annotations]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0    
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --recursive
          - --remove-all-unused-imports
          - --remove-unused-variables
        files: \.py$
