hydra:
  run:
    dir: ${hydra:runtime.cwd}

defaults:
  - __self__

logging:
  level: INFO

data:
  fits_file: "path/to/data.fits"
  sample_size: 600000
  random_seed: 42
  z_range:
    min: 0.43
    max: 0.70
