# configs/datagen/config.yaml
version_base: 1.3         # ← tell Hydra which config schema version you’re targeting

hydra:
  job:
    chdir: false
  run:
    dir: ${hydra:runtime.cwd}

defaults:
  - _self_

logging:
  level: INFO

data:
  fits_file: "data/galaxy_DR12v5_CMASS_North.fits"
  sample_size: 600000
  random_seed: 42
  z_range:
    min: 0.43
    max: 0.70
