defaults:
  - _self_
  - config


images:
  num_test_samples: 2400
  num_train_samples: 9600
  square_size: 0.6
  img_size: 64
  bw_mode: false
  output_dir: all_images/dev_trials
  prefix: boss
  viz:
    enable: true
    output_file: "plots/sample_distribution.png"

logging:
  level: INFO

version_base: 1.3
hydra:
  job:
    chdir: false
  run:
    dir: ${hydra:runtime.cwd}
