defaults:
  - _self_
data:
  fits_file: ../data/…
  sample_size: 500000
  random_seed: 42
  z_range:
    min: 0.43
    max: 0.70
images:
  num_samples: 2400
  square_size: 0.5
  img_size: 64
  bw_mode: false
  output_dir: all_images
  prefix: boss
logging:
  level: INFO
version_base: 1.3
hydra:
  job:
    chdir: false
  run:
    dir: ${hydra:runtime.cwd}
