version_base: 1.3
hydra:
  job:
    chdir: false
  run:
    dir: ${hydra:runtime.cwd}

logging:
  level: INFO

data:
  base_dir: "all_images"
  test_subdir: "dev_trials/test"
  train_subdir: "dev_trials/train"
  mean: [30, 0.001, 28.4]
  std:  [65, 0.01, 47]
  img_size: 64

train:
  lr: 0.001
  momentum: 0.9
  epochs: 5
  batch_size: 64
  num_workers: 4
  flip_augment: true
  checkpoint_dir: "models_lit"
  early_stop_patience: 5
  log_every_n_steps: 5

hardware:
  accelerator: auto    # 'cpu', 'gpu', 'mps', or 'auto'
  devices: 1
  precision: 32        # or 16 for mixed precision
  use_cuda:    false   # set true to try NVIDIA
  use_dml: false  # set true on native Windows w/ DirectML
  use_mps:     false